/**
 * Authoritative 5-Color Unified Visual Design Palette
 * Reference: Implementation Phase 6 Specification
 *
 * WHITE:  #FFFFFF (Global Background)
 * PALE_1: #F5FBDA (Large Panel Background / Light Highlight)
 * PALE_2: #D9EFBD (Secondary Panel / Hover / Sub Area / Medium Tone)
 * ACCENT: #B9D175 (Main Accent / Progress / Active Decoration)
 * DARK:   #450C3F (Primary Text / Border / Icon / Outline / Error)
 */

export const AUTHORITATIVE_PALETTE = {
  WHITE: "#FFFFFF",
  PALE_1: "#F5FBDA",
  PALE_2: "#D9EFBD",
  ACCENT: "#B9D175",
  DARK: "#450C3F"
};

export const PALETTE = {
  // 5 Core Tokens
  WHITE: AUTHORITATIVE_PALETTE.WHITE,
  PALE_1: AUTHORITATIVE_PALETTE.PALE_1,
  PALE_2: AUTHORITATIVE_PALETTE.PALE_2,
  ACCENT: AUTHORITATIVE_PALETTE.ACCENT,
  DARK: AUTHORITATIVE_PALETTE.DARK,

  // Outlines, Shadows & Structural Dark
  OUTLINE_DARK: AUTHORITATIVE_PALETTE.DARK,
  OUTLINE_MED: AUTHORITATIVE_PALETTE.DARK,
  SHADOW: "rgba(69, 12, 63, 0.25)",

  // Forklift (Recolored with ACCENT, PALE_2, DARK, PALE_1)
  FORK_BODY_LIGHT: AUTHORITATIVE_PALETTE.PALE_2,
  FORK_BODY_MAIN: AUTHORITATIVE_PALETTE.ACCENT,
  FORK_BODY_DARK: AUTHORITATIVE_PALETTE.DARK,
  FORK_CABIN: AUTHORITATIVE_PALETTE.DARK,
  FORK_SEAT: AUTHORITATIVE_PALETTE.DARK,
  FORK_MAST: AUTHORITATIVE_PALETTE.DARK,
  FORK_FORKS: AUTHORITATIVE_PALETTE.DARK,

  // Wheels & Hardware
  TIRE_BLACK: AUTHORITATIVE_PALETTE.DARK,
  TIRE_DARK: AUTHORITATIVE_PALETTE.DARK,
  RIM_LIGHT: AUTHORITATIVE_PALETTE.PALE_1,
  RIM_DARK: AUTHORITATIVE_PALETTE.ACCENT,

  // Scaffold Materials & Steel
  STEEL_HIGHLIGHT: AUTHORITATIVE_PALETTE.PALE_1,
  STEEL_LIGHT: AUTHORITATIVE_PALETTE.PALE_2,
  STEEL_MAIN: AUTHORITATIVE_PALETTE.ACCENT,
  STEEL_DARK: AUTHORITATIVE_PALETTE.DARK,
  STEEL_BLUE: AUTHORITATIVE_PALETTE.ACCENT,
  WOOD_PALLET: AUTHORITATIVE_PALETTE.PALE_2,
  WOOD_DARK: AUTHORITATIVE_PALETTE.DARK,
  BAND_STRAP: AUTHORITATIVE_PALETTE.DARK,

  // Trucks (3 difficulty models)
  TRUCK_CAB_WHITE: AUTHORITATIVE_PALETTE.PALE_1,
  TRUCK_CAB_SHADOW: AUTHORITATIVE_PALETTE.PALE_2,
  TRUCK_CHASSIS: AUTHORITATIVE_PALETTE.DARK,
  TRUCK_BED: AUTHORITATIVE_PALETTE.ACCENT,
  CRANE_BLUE: AUTHORITATIVE_PALETTE.ACCENT,
  CRANE_ORANGE: AUTHORITATIVE_PALETTE.DARK,
  GLASS_BLUE: AUTHORITATIVE_PALETTE.PALE_2,
  GLASS_TINT: AUTHORITATIVE_PALETTE.PALE_1,

  // Effects
  SPARK_YELLOW: AUTHORITATIVE_PALETTE.PALE_1,
  SPARK_WHITE: AUTHORITATIVE_PALETTE.WHITE,
  BURST_ORANGE: AUTHORITATIVE_PALETTE.ACCENT,
  MISS_RED: AUTHORITATIVE_PALETTE.DARK,

  // Construction & Background Ground
  CONCRETE_LIGHT: AUTHORITATIVE_PALETTE.PALE_1,
  CONCRETE_MAIN: AUTHORITATIVE_PALETTE.PALE_2,
  CONCRETE_DARK: AUTHORITATIVE_PALETTE.DARK,
  WOOD_FRAME: AUTHORITATIVE_PALETTE.DARK,

  // Container Facility
  CONTAINER_TEAL: AUTHORITATIVE_PALETTE.ACCENT,
  CONTAINER_DARK: AUTHORITATIVE_PALETTE.DARK,

  // House
  HOUSE_WALL: AUTHORITATIVE_PALETTE.PALE_1,
  HOUSE_ROOF: AUTHORITATIVE_PALETTE.ACCENT,
  HOUSE_DOOR: AUTHORITATIVE_PALETTE.DARK,

  // Mid-Rise Office Building
  BUILDING_WALL: AUTHORITATIVE_PALETTE.PALE_2,
  BUILDING_WINDOW: AUTHORITATIVE_PALETTE.PALE_1,
  BUILDING_DARK: AUTHORITATIVE_PALETTE.DARK,

  // Highrise Skyscraper
  HIGHRISE_GLASS: AUTHORITATIVE_PALETTE.ACCENT,
  HIGHRISE_DARK: AUTHORITATIVE_PALETTE.DARK,
  HIGHRISE_ACCENT: AUTHORITATIVE_PALETTE.PALE_2,

  // Tokyo Tower
  TOWER_RED: AUTHORITATIVE_PALETTE.DARK,
  TOWER_WHITE: AUTHORITATIVE_PALETTE.PALE_1,
  TOWER_LIGHT: AUTHORITATIVE_PALETTE.ACCENT,

  // Skytree
  SKYTREE_WHITE: AUTHORITATIVE_PALETTE.PALE_1,
  SKYTREE_STEEL: AUTHORITATIVE_PALETTE.ACCENT,
  SKYTREE_CYAN: AUTHORITATIVE_PALETTE.PALE_2
};
